### ISSUE TITLE
Error transforming abi for `atomicassets`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/antelope-abi2rs#9]
```
$ eosc -u https://eos.greymass.com get abi atomicassets | antelope-abi2rs src/abi.rs

Variants are not supported, skipping variant_int8_int16_int32_int64_uint8_uint16_uint32_uint64_float32_float64_string_INT8_VEC_INT16_VEC_INT32_VEC_INT64_VEC_UINT8_VEC_UINT16_VEC_UINT32_VEC_UINT64_VEC_FLOAT_VEC_DOUBLE_VEC_STRING_VEC
Error transforming abi: struct.fields is not iterable%
```

**Comment by YaroShkvorets** [comment]
Fixed in v0.4.1

**Comment by Pelotfr** [comment]
Hi, I still have the variant not supported, the abi.rs is created but with the type ATOMICATTRIBUTE that will yield an error during compilation. 

abi generation:
![image](https://github.com/pinax-network/antelope-abi2rs/assets/65423129/50f0528c-3b6a-4a10-baed-21062aa70cd2)

field generated and compilation error:
![image](https://github.com/pinax-network/antelope-abi2rs/assets/65423129/502a315c-3cd5-4ffc-848e-9e7c248c1274)

I do not need this type for my use case right now so I will look for a temporary fix (comment it out probably)
